language: php

cache:
    directories:
        $HOME/.composer/cache/files

php:
    - 7.0
    - 7.1

install:
    - php -n ~/.phpenv/versions/$(phpenv version-name)/bin/composer self-update
    - php -n ~/.phpenv/versions/$(phpenv version-name)/bin/composer require satooshi/php-coveralls
    - php -n ~/.phpenv/versions/$(phpenv version-name)/bin/composer update

script:
    - php -n ~/.phpenv/versions/$(phpenv version-name)/bin/composer lint
    - php -n ~/.phpenv/versions/$(phpenv version-name)/bin/composer test -- --coverage-clover build/logs/clover.xml

after_success:
    - travis_retry php -n vendor/bin/coveralls
